services:
  - type: web
    name: promethios-landing
    env: static
    runtime: node
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

