name: Sequential Phase Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-phases:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run sequential phase validation
      run: |
        python scripts/validate_phases.py --verbose --report
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          test_results/validation_report.md
          test_results/validation_results.json
        
    - name: Check validation status
      run: |
        if [ ! -f test_results/validation_results.json ]; then
          echo "Validation results not found!"
          exit 1
        fi
        
        # Check if validation was successful
        SUCCESS=$(python -c "import json; print(json.load(open('test_results/validation_results.json'))['success'])")
        
        if [ "$SUCCESS" = "True" ]; then
          echo "✅ Phase validation successful!"
          exit 0
        else
          echo "❌ Phase validation failed!"
          cat test_results/validation_report.md
          exit 1
        fi
